title: tabneib.github.io
#email: 
description: >- # ignore new lines
    Learning by doing, not memorization
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tabneib.github.io"
#twitter_username: 
github_username:  tabneib

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
